AllCops:
  TargetRubyVersion: 2.5

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 170

Metrics/PerceivedComplexity:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true
