# This is the websites config file written in YAML http://yaml.org/

# site config
url: http://thebeast.me/charts/
about: "This Ruby script is a static site generator. It text mines a folder of XML Schema as well as the MIT License and generates statistics on elements, attributes (XML) or words (License). The config file: site.yml stores most of the websites configuration information and can be easily customized."
last_update: "Site last built: "
valid_html: Valid HTML
back_to_top: Back to top
text_color: '000'
logo_text_color: 'ff00ff'
nav_hover_color: red
nav_selected_color: aliceblue

maps: http://www.sitemaps.org/schemas/sitemap/0.9


# GitHub details
github_username: jbampton
repository: charts


# HTML elements and attributes
# meta name="description"
description: Analytics dashboard built from Ruby using the d3pie library. It text mines a folder of XML Schema to generate statistics about tags and attributes.
# <title>
title: Ruby d3pie text mining dashboard
# meta name="theme-color"
theme_color: E5E8E8


# Text on web pages
# heading at top left of website
nav_heading: Analytics Dashboard
# homepage heading h1
homepage_heading: Ruby d3pie based XML Schema text mining application
# heading on other pages h1
other_heading: Branch count grouped by file

# homepage subheading1 h2
homepage_subheading1: Featured Statistics
# homepage subheading2 h3
homepage_subheading2: About
# homepage subheading3 h3
homepage_subheading3: Built With
# homepage subheading4 h3
homepage_subheading4: Lines of code in this project
