# This is the websites config file written in YAML http://yaml.org/

# site config
url: http://thebeast.me/charts/
# chart type: either "d3pie" or "google" or "chartjs"
chart_type: chartjs
# about section is marked up in Markdown format
# https://daringfireball.net/projects/markdown/
about: "### About


This Ruby script `run.rb` is a static site generator. It data mines or text mines a folder of XML Schema files as well as the MIT License and generates statistics on elements and attributes (the XML Schema) or on words (the License).


The config file: `site.yml` stores most of the websites configuration information and can be easily customized.


A fancy feature is the ability to switch between using **`d3pie`**, **`Google Charts`** or **`Chart.js`** based pie charts just by changing the config entry `chart_type` from **`d3pie`** to **`google`** or to **`chartjs`**.


The home page charts for the **`Google Charts`** and **`Chart.js`** `chart_type` are not yet complete.


For all three styles of pie charts we have both `Donut` and `Pie` style charts.


The advantage of the **`d3pie`** chart is its ability to handle mouse clicks on the pie chart pieces and they respond by popping in and out.


The advantage of the **`Google Chart`** pie chart is its in built ability to create a chart legend.


The advantage of the **`Chart.js`** pie chart is its interactive clickable legend.


This section is written in Markdown format coming from the site config file: `site.yml` and I am using kramdown to convert it to HTML.


### Built With

"

last_update: "Site last built: "
valid_html: Valid HTML
back_to_top: Back to top
text_color: '000'
logo_text_color: 'ff00ff'
nav_hover_color: red
nav_selected_color: aliceblue

maps: http://www.sitemaps.org/schemas/sitemap/0.9


# GitHub details
github_username: jbampton
repository: charts


# HTML elements and attributes
# meta name="description"
description: Analytics dashboard built from Ruby using the d3pie and Google charts libraries. The application or script text mines a folder of XML Schema to generate statistics about tags and attributes.
# <title>
title: Ruby d3pie text mining dashboard
# meta name="theme-color"
theme_color: E5E8E8


# Text on web pages
# heading at top left of website
nav_heading: Analytics Dashboard
# homepage heading h1
homepage_heading: Ruby d3pie based XML Schema text mining application
# heading on other pages h1
other_heading: Branch count grouped by file

# homepage subheading1 h2
homepage_subheading1: Featured Statistics

# homepage subheading4 h3
homepage_subheading4: Lines of code in this project
