# This is the websites config file written in YAML http://yaml.org/

# site config
url: http://thebeast.me/charts/
# chart type: either "d3pie" or "google" or "chartjs" or "plotly"
chart_type: plotly
# about section is marked up in Markdown format
# https://daringfireball.net/projects/markdown/
about: "### About


This Ruby script **`run.rb`** is a static site generator. It data mines or text mines a folder of XML Schema files as well as the MIT License (only for the d3pie charts) and generates statistics on elements and attributes (the XML Schema) or on words (the License).


The config file: **`site.yml`** stores most of the websites configuration information and can be easily customized.


A fancy feature is the ability to switch between using d3pie, Google Charts, Chart.js or plotly.js based pie charts just by changing the config entry **`chart_type`** to one of **`d3pie`**, **`google`**, **`chartjs`** or **`plotly`**.


The home page charts for the Google Charts, Chart.js and plotly.js **`chart_type`** are not yet complete.


For all four styles of pie charts we have both **`Donut`** and **`Pie`** style charts.


The advantage of the d3pie chart is its interactive clickable pie charts pieces.


The advantage of the Google Chart pie chart is its in built ability to create a chart legend.


The advantage of the Chart.js pie chart is its interactive clickable legend.


The plotly.js pie charts are by far the most interactive out of the box.


This section is written in Markdown format coming from the site config file: **`site.yml`** and I am using kramdown to convert it to HTML.


### Built With

"

#
last_update: "Site last built: "
valid_html: Valid HTML
back_to_top: Back to top
text_color: '000'
logo_text_color: 'ff00ff'
nav_hover_color: red
nav_selected_color: aliceblue

maps: http://www.sitemaps.org/schemas/sitemap/0.9


# GitHub details
github_username: jbampton
repository: charts


# HTML elements and attributes
# meta name="description"
description: Analytics dashboard built from Ruby using the d3pie, Google charts and Chart.js libraries. The application or script text mines a folder of XML Schema to generate statistics about tags and attributes.
# <title>
title: Text mining analytics dashboard and static site generator
# meta name="theme-color"
theme_color: E5E8E8


# Text on web pages
# heading at top left of website
nav_heading: Analytics Dashboard
# homepage heading h1
homepage_heading: "**`Ruby`** based **`d3pie`**, **`Google Charts`**, **`Chart.js`** and **`plotly.js`** XML Schema text mining configurable static site generator"
# chart pages heading h1
chart_pages_heading: "Chart type: **`d3pie`**"
# heading on other pages h1
other_heading: Branch count grouped by file

# homepage subheading1 h2
homepage_subheading1: Featured Statistics

# homepage subheading4 h3
homepage_subheading4: Lines of code in this project
